### ISSUE TITLE
error after importing rest

### ISSUE THREAD

**Issue by moepi2k** [insthync/unity-rest-client#1]
after importing rest client i got a namepsace error

https://gyazo.com/92aca8d6b81505ec2ebdb0d0cfdd0e11

any idea?

**Comment by insthync** [comment]
https://github.com/jilleJr/Newtonsoft.Json-for-Unity

**Comment by moepi2k** [comment]
ohh thank you, didnt found that step :)

**Comment by insthync** [comment]
Everyone who works with C# would know it.
