### ISSUE TITLE
Endpoints updated here but updates not reflected in Auction House addon.

### ISSUE THREAD

**Issue by Leerael** [insthync/unity-rest-client#2]
Endpoints updated here but updates not reflected in Auction House addon.

Can see you merged the updates to the endpoints into master on here but assuming you were updating the endpoints in the auction house addons and hadn't pushed them yet.

**Comment by insthync** [comment]
Fixed, you have to update the auction house, thank you :)

**Comment by Leerael** [comment]
awesome thank you.
